CREATE TABLE IF NOT EXISTS DB_VERSIONS (
    VERSION_NUMBER INT NOT NULL,
    REC_CREAT_DT_TM TIMESTAMP NOT NULL
);

ALTER TABLE DB_VERSIONS ADD PRIMARY KEY (VERSION_NUMBER);

-- point to the newest version when first init
INSERT INTO DB_VERSIONS(VERSION_NUMBER, REC_CREAT_DT_TM) VALUES (1, now());

CREATE TABLE IF NOT EXISTS DEMO_MESSAGE (
    MESSAGE_ID INT NOT NULL,
    MESSAGE VARCHAR(256) NOT NULL,
    REC_MODIFIED_DT_TM TIMESTAMP NOT NULL
);

ALTER TABLE DEMO_MESSAGE ADD PRIMARY KEY (MESSAGE_ID);
